version: "3"
services:
  web:
    # replace shamikb18/docker-test:part1 with your name and image details
    image: shamikb18/docker-test:part1
    deploy:
      replicas: 7
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "80:80"
    networks:
      - webnet
networks:
  webnet:
